import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopNav() {
  return (
    <nav className="absolute flex h-16 w-full items-center justify-start bg-slate-950/50 px-4 font-sans font-semibold shadow-md backdrop-blur">
      <Link href="/" className="drop-shadow">
        Home
      </Link>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen`}>
        <TopNav />
        <div className="h-full w-full overflow-auto pt-20">{children}</div>
      </body>
    </html>
  );
}
